version: "2"

linters-settings:
  govet:
    disable:
      - fieldalignment

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  exclusions:
    paths:
      - vendor
      - third_party
    files:
      - ".*_test\\.go$"
