version: "2"

linters-settings:
  govet:
    disable:
      - fieldalignment

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  exclusions:
    paths:
      - vendor
    rules:
      - path: _test\.go
        linters:
          - errcheck
